version: '3.8'

services:

  wordpress:
    image: wordpress
    container_name: wordpressakanni
    ports:
      - "78.142.242.175:8181:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db

  mysql:
    image: mysql
    container_name: mysqlakanni
    ports:
      - "78.142.242.175:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password