version: '3.8'
services:

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Siimmpplles99@
      MYSQL_DATABASE: wpakanni
      MYSQL_USER: wpakanni
      MYSQL_PASSWORD: Siimmpplles99@
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - ""
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpakanni.mysql.dbaas.com.br
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: wordpress_db_password
      WORDPRESS_DB_NAME: wordpress_local
volumes:
  db_data: {}
  wordpress_data: {}